version: '3'
services:
  db:
    container_name: postgres
    restart: always
    image: postgres
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./initDB:/docker-entrypoint-initdb.d/
    ports:
      - 5435:5432